### ISSUE TITLE
Minor issue in unit tests for non English environments

### ISSUE THREAD

**Issue by opterios** [ChrisKlug/efcore-dto-demo#2]
Hi Chris,

First of all, let me say that the talk was super interesting to me and very useful in many ways. I really like the approach that the DbContext can (and maybe should) be your repository. I also liked the Result.Success/Fail perk.

I found a minor localization issue in a test unit. It is super easy to fix, so I thought I'd just mention it. When I ran the tests on my environment, some of the tests crashed with the SQL Error "Conversion failed when converting date and/or time from character string.".

I found out that the issue is in the AddVehicle() method, where you insert a VehicleOwners record and you let the date fields serialize with the default behaviour (line 42), i.e. using the local regional settings. My regional settings are Greek, so the materialized SQL script was: "INSERT INTO VehicleOwners (VehicleId, PersonId, [From], [To]) VALUES (1,1,'4/7/2013 12:00:00 πμ','2/7/2023 12:00:00 πμ')".

Just putting owner.From.ToString("yyyyMMdd") and owner.To?.ToString("yyyyMMdd") resolves the issue, in case anybody else wants to run the tests in non English machines.

**Comment by ChrisKlug** [comment]
Thank you for the feedback! Would this PR solve it for you?

**Comment by opterios** [comment]
Yes, that fixed it up! Thanks!
